'use client';

import Link from 'next/link';
import { useState } from 'react';
import { CHECK_QUESTIONS } from '@/lib/courses';

const tokenKey = (courseId) => `moleskill:${courseId}:learner`;
const makeToken = () => crypto.randomUUID?.() || 'xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx'.replace(/[xy]/g, c => { const r = Math.random() * 16 | 0; return (c === 'x' ? r : (r & 3) | 8).toString(16); });

function Test({ stage, courseId, onDone }) {
  const [answers, setAnswers] = useState({}); const [saving, setSaving] = useState(false); const [error, setError] = useState('');
  async function submit(e) { e.preventDefault(); if (Object.keys(answers).length !== CHECK_QUESTIONS.length) return setError('Выберите ответ на каждый вопрос.'); setSaving(true); setError(''); try { let learnerToken = localStorage.getItem(tokenKey(courseId)); if (!learnerToken) { learnerToken = makeToken(); localStorage.setItem(tokenKey(courseId), learnerToken); } const res = await fetch('/api/course-assessment', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ courseId, stage, learnerToken, answers }) }); const data = await res.json(); if (!res.ok || !data.ok) throw new Error(data.error || 'Не удалось отправить тест.'); onDone(data.score, data.total); } catch (err) { setError(err.message); } finally { setSaving(false); } }
  return <section className="test-card"><p className="ms-kicker"><span>{stage === 'before' ? 'Перед стартом' : 'Финальная проверка'}</span> Анонимный тест</p><h1>{stage === 'before' ? 'Проверим точку старта' : 'Закрепим результат'}</h1><p className="test-lead">5 вопросов, около минуты. Имя и контакты не собираем.</p><form onSubmit={submit}>{CHECK_QUESTIONS.map((question, index) => <fieldset key={question.id}><legend>{index + 1}. {question.text}</legend>{question.options.map((option, optionIndex) => <label className="test-option" key={option}><input type="radio" name={question.id} checked={answers[question.id] === optionIndex} onChange={() => setAnswers({ ...answers, [question.id]: optionIndex })} /><span>{option}</span></label>)}</fieldset>)}{error && <p className="error">{error}</p>}<button className="ms-button" disabled={saving}>{saving ? 'Сохраняем…' : stage === 'before' ? 'Начать курс →' : 'Завершить курс →'}</button></form></section>;
}

export default function CoursePlayer({ course }) {
  const [state, setState] = useState('welcome'); const [lesson, setLesson] = useState(0); const [score, setScore] = useState(null); const [measured, setMeasured] = useState(false); const [challengeOpen, setChallengeOpen] = useState(false);
  if (state === 'welcome') return <main className="course-page"><Link className="back-link" href="/">← Все курсы</Link><section className={`course-intro ${course.color}`}><p>{course.number} · {course.duration}</p><h1>{course.title}</h1><p>{course.description}</p><div className="consent-box"><b>Тест — по желанию, курс доступен всем.</b><span>Если согласишься, анонимные результаты до и после помогут нам понять, насколько курс полезен. Мы не собираем имя, почту или телефон.</span></div><div className="intro-actions"><button className="ms-button" onClick={() => setState('before')}>Пройти тест и начать →</button><button className="ms-button ms-button-light" onClick={() => setState('lesson')}>Начать без теста →</button></div><Link href="/" className="decline-link">Вернуться к курсам</Link></section></main>;
  if (state === 'before') return <main className="course-page"><Link className="back-link" href="/">← Все курсы</Link><Test stage="before" courseId={course.id} onDone={() => { setMeasured(true); setState('lesson'); }} /></main>;
  if (state === 'after') return <main className="course-page"><Link className="back-link" href="/">← Все курсы</Link><Test stage="after" courseId={course.id} onDone={(value) => { setScore(value); setState('done'); }} /></main>;
  if (state === 'done') return <main className="course-page"><section className="test-card done-card"><p className="ms-kicker"><span>Готово</span> {measured ? 'Результат сохранён анонимно' : 'Курс пройден'}</p><h1>Ты прошёл курс!</h1><p>{measured ? <>Финальный результат: <b>{score} из 5</b>. Он войдёт только в общую статистику эффективности обучения.</> : 'Спасибо за обучение. Тест не обязателен — твой прогресс никуда не отправлялся.'}</p><Link className="ms-button" href="/">Выбрать следующий курс →</Link></section></main>;
  const item = course.lessons[lesson]; const last = lesson === course.lessons.length - 1;
  return <main className="course-page"><Link className="back-link" href="/">← Все курсы</Link><div className="lesson-progress"><span style={{ width: `${((lesson + 1) / course.lessons.length) * 100}%` }} /></div><article className="lesson-card"><p className="ms-kicker"><span>Урок {lesson + 1}</span> из {course.lessons.length}</p><div className={`lesson-mark ${course.color}`}>✦</div><h1>{item.title}</h1><p>{item.text}</p><ul className="lesson-points">{item.points.map((point) => <li key={point}>{point}</li>)}</ul><button className="practice-toggle" onClick={() => setChallengeOpen(!challengeOpen)}>{challengeOpen ? 'Скрыть практику' : 'Мини-практика'} <span>⌄</span></button>{challengeOpen && <div className="practice-card"><b>Попробуй сейчас</b><p>{item.challenge}</p><textarea aria-label="Мой ответ на мини-практику" placeholder="Напиши свой ответ — он остаётся только в этом браузере." /></div>}<div className="lesson-actions">{lesson > 0 && <button className="ms-text-button" onClick={() => { setChallengeOpen(false); setLesson(lesson - 1); }}>← Назад</button>}<button className="ms-button" onClick={() => { if (last) setState(measured ? 'after' : 'done'); else { setChallengeOpen(false); setLesson(lesson + 1); } }}>{last ? (measured ? 'Пройти финальный тест →' : 'Завершить курс →') : 'Следующий урок →'}</button></div></article></main>;
}
